create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  full_name text not null default '',
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', '')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and is_admin = true
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  order_number bigint generated by default as identity (start with 1001),
  user_id uuid not null default auth.uid() references auth.users (id) on delete restrict,
  customer_name text not null,
  customer_email text not null,
  detail text not null,
  total integer not null check (total >= 0),
  status text not null default 'Recibido'
    check (status in ('Recibido', 'En preparación', 'Listo para entregar', 'Entregado')),
  delivery_city text not null,
  delivery_address text not null,
  delivery_zone text not null,
  payment_method text not null,
  created_at timestamptz not null default now(),
  primary key (order_number)
);

alter table public.orders alter column user_id set default auth.uid();
alter table public.orders drop constraint if exists orders_total_check;
alter table public.orders drop constraint if exists orders_positive_total;
alter table public.orders add constraint orders_positive_total check (total > 0) not valid;
alter table public.orders drop constraint if exists orders_valid_delivery_zone;
alter table public.orders add constraint orders_valid_delivery_zone
  check (delivery_zone in ('envigado', 'medellin', 'sabaneta', 'bello')) not valid;
alter table public.orders drop constraint if exists orders_valid_payment_method;
alter table public.orders add constraint orders_valid_payment_method
  check (payment_method in ('contraentrega', 'transferencia', 'tarjeta')) not valid;

create or replace function public.set_order_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_name text;
  current_email text;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required';
  end if;

  select coalesce(nullif(profile.full_name, ''), auth_user.email), auth_user.email
    into current_name, current_email
    from auth.users as auth_user
    left join public.profiles as profile on profile.id = auth_user.id
    where auth_user.id = (select auth.uid());

  if current_email is null then
    raise exception 'Authenticated profile not found';
  end if;

  new.user_id := (select auth.uid());
  new.customer_name := current_name;
  new.customer_email := current_email;
  new.status := 'Recibido';
  new.created_at := now();
  return new;
end;
$$;

drop trigger if exists set_order_identity_before_insert on public.orders;
create trigger set_order_identity_before_insert
  before insert on public.orders
  for each row execute procedure public.set_order_identity();

revoke all on function public.set_order_identity() from public;

alter table public.profiles enable row level security;
alter table public.app_settings enable row level security;
alter table public.orders enable row level security;

revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;

revoke all on public.app_settings from anon, authenticated;
grant select on public.app_settings to anon, authenticated;
grant insert, update, delete on public.app_settings to authenticated;

revoke all on public.orders from anon, authenticated;
grant select on public.orders to authenticated;
grant insert (detail, total, delivery_city, delivery_address, delivery_zone, payment_method)
  on public.orders to authenticated;
grant update (status) on public.orders to authenticated;

drop policy if exists "Users read own profile or admins read all" on public.profiles;
create policy "Users read own profile or admins read all"
  on public.profiles for select to authenticated
  using ((select auth.uid()) = id or (select public.is_admin()));

drop policy if exists "Public reads storefront settings" on public.app_settings;
create policy "Public reads storefront settings"
  on public.app_settings for select to anon, authenticated
  using (key in ('adminCatalogo', 'adminPrecios', 'adminCategorias') or (select public.is_admin()));

drop policy if exists "Admins insert settings" on public.app_settings;
create policy "Admins insert settings"
  on public.app_settings for insert to authenticated
  with check ((select public.is_admin()));

drop policy if exists "Admins update settings" on public.app_settings;
create policy "Admins update settings"
  on public.app_settings for update to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

drop policy if exists "Admins delete settings" on public.app_settings;
create policy "Admins delete settings"
  on public.app_settings for delete to authenticated
  using ((select public.is_admin()));

drop policy if exists "Customers create their own orders" on public.orders;
create policy "Customers create their own orders"
  on public.orders for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Customers read own orders and admins read all" on public.orders;
create policy "Customers read own orders and admins read all"
  on public.orders for select to authenticated
  using ((select auth.uid()) = user_id or (select public.is_admin()));

drop policy if exists "Admins update orders" on public.orders;
create policy "Admins update orders"
  on public.orders for update to authenticated
  using ((select public.is_admin()))
  with check ((select public.is_admin()));

insert into public.app_settings (key, value) values
  ('adminCatalogo', '[{"index":0,"n":"Sushi roll clásico","cat":"asiatico","p":28000},{"index":2,"n":"Ramen de cerdo","cat":"asiatico","p":30000},{"index":14,"n":"Hummus con pan pita","cat":"oriental","p":18000},{"index":29,"n":"Pasta carbonara","cat":"europeo","p":28000},{"index":44,"n":"Bandeja paisa","cat":"latino","p":35000},{"index":59,"n":"Hamburguesa clásica","cat":"rapido","p":22000},{"index":74,"n":"Ensalada César vegetariana","cat":"vegetariano","p":20000},{"index":89,"n":"Hamburguesa vegana","cat":"vegano","p":24000}]'::jsonb),
  ('adminPrecios', '{}'::jsonb),
  ('adminCategorias', '{}'::jsonb),
  ('adminInventario', '{}'::jsonb)
on conflict (key) do nothing;

-- Después de registrar la cuenta que administrará la tienda, asígnale permisos desde el SQL Editor:
-- update public.profiles set is_admin = true where email = 'tu-correo@ejemplo.com';
